// Auto-generated by Supabase CLI. Do not edit manually.
// Regenerate with: npx supabase gen types typescript --project-id laivjijxoanhimjzurmn > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      applications: {
        Row: {
          application_status: string | null
          company_name: string
          cover_letter_length: string | null
          cover_letter_max_words: number | null
          created_at: string | null
          documents_requested: string[]
          hiring_manager_name: string | null
          id: string
          job_description: string
          job_title: string
          job_url: string | null
          notes: string | null
          status: string | null
          tone: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          application_status?: string | null
          company_name: string
          cover_letter_length?: string | null
          cover_letter_max_words?: number | null
          created_at?: string | null
          documents_requested?: string[]
          hiring_manager_name?: string | null
          id?: string
          job_description: string
          job_title: string
          job_url?: string | null
          notes?: string | null
          status?: string | null
          tone?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          application_status?: string | null
          company_name?: string
          cover_letter_length?: string | null
          cover_letter_max_words?: number | null
          created_at?: string | null
          documents_requested?: string[]
          hiring_manager_name?: string | null
          id?: string
          job_description?: string
          job_title?: string
          job_url?: string | null
          notes?: string | null
          status?: string | null
          tone?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      documents: {
        Row: {
          application_id: string
          content: string | null
          created_at: string | null
          edited_content: string | null
          id: string
          status: string | null
          type: string
          user_id: string
          version: number
        }
        Insert: {
          application_id: string
          content?: string | null
          created_at?: string | null
          edited_content?: string | null
          id?: string
          status?: string | null
          type: string
          user_id: string
          version?: number
        }
        Update: {
          application_id?: string
          content?: string | null
          created_at?: string | null
          edited_content?: string | null
          id?: string
          status?: string | null
          type?: string
          user_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "documents_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          career_aspirations: string | null
          certifications: Json | null
          cover_letter_template: string | null
          culture_values: string[] | null
          education: Json | null
          email_notifications: boolean | null
          full_name: string | null
          headline: string | null
          hobbies_interests: string | null
          id: string
          linkedin_url: string | null
          location: string | null
          onboarding_complete: boolean | null
          phone: string | null
          preferred_tone: string | null
          skills_experiences: Json | null
          summary: string | null
          target_industries: string[] | null
          target_roles: string[] | null
          updated_at: string | null
          user_id: string
          work_history: Json | null
        }
        Insert: {
          career_aspirations?: string | null
          certifications?: Json | null
          cover_letter_template?: string | null
          culture_values?: string[] | null
          education?: Json | null
          email_notifications?: boolean | null
          full_name?: string | null
          headline?: string | null
          hobbies_interests?: string | null
          id?: string
          linkedin_url?: string | null
          location?: string | null
          onboarding_complete?: boolean | null
          phone?: string | null
          preferred_tone?: string | null
          skills_experiences?: Json | null
          summary?: string | null
          target_industries?: string[] | null
          target_roles?: string[] | null
          updated_at?: string | null
          user_id: string
          work_history?: Json | null
        }
        Update: {
          career_aspirations?: string | null
          certifications?: Json | null
          cover_letter_template?: string | null
          culture_values?: string[] | null
          education?: Json | null
          email_notifications?: boolean | null
          full_name?: string | null
          headline?: string | null
          hobbies_interests?: string | null
          id?: string
          linkedin_url?: string | null
          location?: string | null
          onboarding_complete?: boolean | null
          phone?: string | null
          preferred_tone?: string | null
          skills_experiences?: Json | null
          summary?: string | null
          target_industries?: string[] | null
          target_roles?: string[] | null
          updated_at?: string | null
          user_id?: string
          work_history?: Json | null
        }
        Relationships: []
      }
      usage: {
        Row: {
          applications_generated: number | null
          id: string
          period: string
          user_id: string
        }
        Insert: {
          applications_generated?: number | null
          id?: string
          period: string
          user_id: string
        }
        Update: {
          applications_generated?: number | null
          id?: string
          period?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
